- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - git
    - gcc
    - python-devel
    - libselinux-python
    - python-devel
    - python-setuptools
    - python-pip
- name: install ansible
  pip: name=ansible state=latest
- name: git clone (rankforce)
  git: "repo={{ git_uri }} version={{ branch }} dest={{ workdir }} update=yes accept_hostkey=yes"
- name: provisioning (rankforce)
  shell: "ansible-playbook -i 'localhost,' {{ workdir }}/ansible/setup-ruby2.2.yml"
