# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # rankforce-test
  config.vm.define "rankforce-test" do |node|
    node.vm.box = "bento/centos-7.1"
    node.vm.hostname = "rankforce-test"
    node.vm.network :public_network, ip: "192.168.0.208", bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: 2234

    config.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible/setup.yml"
      ansible.tags = "ruby2.2"
      ansible.host_key_checking = false
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end
end
