- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - git
    - gcc
    - python-devel
    - libselinux-python
    - docker
- name: restart docker
  service: name=docker state=restarted
- name: docker container clear
  shell: docker ps -a | grep '{{ item }}' | awk '{print $1}' | xargs --no-run-if-empty docker rm -f
  with_items:
    - rankforce
  sudo: yes
