- name: get rankforce from repository
  git: "repo={{ repo_uri }} version={{ branch }} dest={{ source_dir }} update=yes accept_hostkey=yes"
- name: bundle install
  shell: bundle install chdir={{ source_dir }}
- name: copy config files
  copy: src="/root/secret_keys/rankforce/{{ item }}" dest=/root/rankforce/config
  with_items:
    - bitly.auth.yml
    - evernote.auth.yml
    - mongolab.test.yml
    - twitter.auth.test.yml
