- name: get rankforce from repository
  tags: always
  git: "repo={{ repo_uri }} version={{ branch }} dest={{ source_dir }} update=yes accept_hostkey=yes"
- name: rewrite Gemfile
  tags: ruby2.0
  lineinfile: >-
    dest="{{ source_dir }}/Gemfile"
    state=present
    regexp='^ruby.*'
    line='ruby 2.0.0'
- name: rewrite Gemfile
  tags: ruby2.1
  lineinfile: >-
    dest="{{ source_dir }}/Gemfile"
    state=present
    regexp='^ruby.*'
    line='ruby 2.1.7'
- name: rewrite Gemfile
  tags: ruby2.2
  lineinfile: >-
    dest="{{ source_dir }}/Gemfile"
    state=present
    regexp='^ruby.*'
    line='ruby 2.2.3'
- name: bundle install
  tags: always
  shell: bundle install chdir={{ source_dir }}
- name: copy config files
  tags: always
  copy: src="/root/secret_keys/rankforce/{{ item }}" dest=/root/rankforce/config
  with_items:
    - bitly.auth.yml
    - evernote.auth.yml
    - mongolab.test.yml
    - twitter.auth.test.yml
